language: python
sudo: required
python:
    - "2.7"
services:
  - docker

#before_install:
#  - docker-compose -f test.yml build
install:
  - bash bin/travis-build.bash
  - pip install coveralls
script:
  - docker-compose -f test.yml up -d --build
  - sh bin/travis-run.sh
after_success:
    - coveralls
