language: python
sudo: required
python:
    - "2.7"
services:
  - docker
env:
  - PGPASSWORD=ckan
install:
  - bash bin/travis-build.bash
script:
  - docker-compose -f test.yml up -d --build
  - docker-compose -f test.yml ps
  - docker-compose -f test.yml exec test_ckan /bin/bash -c "export PGPASSWORD=ckan; until psql -q -h test_db -U ckan_default -d ckan_test -c 'select * from user;'; do echo 'db unavailable. sleeping'; sleep 1; done"
  - docker-compose -f test.yml exec test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckanext-report report initdb -c /etc/ckan/test.ini
  - docker-compose -f test.yml exec test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckan create-test-data
  - docker-compose -f test.yml exec test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckan create-test-data search
  - docker-compose -f test.yml exec test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckan create-test-data gov
  - docker-compose -f test.yml exec test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckanext-ga-report initdb -c /etc/ckan/test.ini
  - docker-compose -f test.yml exec test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckanext-defra import_publishers -c /etc/ckan/test.ini
  - docker-compose -f test.yml exec test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckanext-report report generate -c /etc/ckan/test.ini
  - docker-compose -f test.yml run --rm test_selenium /deploy/compose/selenium/run_tests.sh; echo $?
