language: python
sudo: required
python:
    - "2.7"
services:
  - docker

before_install:
  - docker-compose -f test.yml build
install:
  - bash bin/travis-build.bash
  - pip install coveralls
script:
  - docker-compose -f test.yml up -d --build
  - docker-compose ps
#  - docker-compose exec dbbackup /bin/bash -c "until psql -l; do echo 'db unavailable. sleeping'; sleep 1; done"
  - sh bin/travis-run.sh
after_success:
    - coveralls
