language: python
sudo: required
python:
    - "2.7"
services:
  - docker

before_install:
  - docker-compose -f test.yml build
install:
  - bash bin/travis-build.bash
  - pip install coveralls
script:
  - docker-compose -f test.yml up -d --build
  - docker-compose -f test.yml ps
  - docker-compose -f test.yml run --rm test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckan create-test-data
  - docker-compose -f test.yml run --rm test_ckan /usr/lib/ckan/venv/bin/paster --plugin=ckanext-report report generate -c /etc/ckan/test.ini
  - sh bin/travis-run.sh
after_success:
    - coveralls
