# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

volumes:
  test_pg_data:
  test_ckan_storage:

services:
  test_ckan:
    container_name: mdf-test-ckan
    build:
      context: .
      dockerfile: compose/ckan/Dockerfile-test
    env_file:
      - .envs/test.env
    volumes:
      - test_ckan_storage:/var/lib/ckan
    links:
      - test_db
      - test_solr
      - test_redis
      - test_location
    command:
      /usr/lib/ckan/venv/bin/paster serve /etc/ckan/test.ini --reload

  test_db:
    container_name: mdf-test-db
    hostname: test_db
    restart: "no"
    build:
      context: .
      dockerfile: compose/postgresql/Dockerfile
    env_file:
      - .envs/test.env
    volumes:
      - test_pg_data:/var/lib/postgresql/data
    expose:
      - "5432"

  test_solr:
    container_name: mdf-test-solr
    restart: "no"
    build:
      context: .
      dockerfile: compose/solr/Dockerfile

  test_redis:
    container_name: mdf-test-redis
    restart: "no"
    image: redis:latest

  test_location:
    container_name: mdf-test-location
    restart: "no"
    build:
      context: .
      dockerfile: compose/location/Dockerfile-test
    env_file:
      - .envs/test.env
    expose:
      - 5000

  test_selenium:
    container_name: mdf-test-selenium
    restart: "no"
    build:
      context: .
      dockerfile: compose/selenium/Dockerfile
    environment:
      - TRAVIS=1
    env_file:
      - .envs/test.env
    volumes:
      - test_ckan_storage:/var/lib/ckan
    links:
      - test_ckan
      - test_db
    command: make --directory /go/src/location-lookup run
