---
# Tasks for postgres

- name: install packages for Postgres/Postgis
  become: true
  apt:
      pkg: "{{ item }}"
      state: present
      update_cache: true
  with_items:
    - postgresql
    - postgis
    - python-psycopg2

- name: Create DB User 
  become: true
  become_user: postgres
  postgresql_user: 
    name: ckan_default
    role_attr_flags: NOCREATEDB,NOCREATEROLE

- name: Create DB 
  become: true
  become_user: postgres
  postgresql_db:
    name: ckan_default
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    owner: ckan_default

- name: Install postgis
  become: true
  become_user: postgres
  postgresql_ext:
    name: postgis
    db: ckan_default
    
- name: Copy the auth file 
  become: true
  become_user: postgres
  template:
      src: files/pg_hba.conf
      dest: /etc/postgresql/9.5/main/pg_hba.conf
  notify: restart postgres
