FROM ckan/ckan:latest

# Copy production.ini over so it's accessiblele during build
COPY ./compose/ckan/config/production.ini /etc/ckan/production.ini

# Install ckan
COPY ./compose/ckan/requirements.txt /requirements.txt
RUN /usr/lib/ckan/venv/bin/pip install -r /usr/lib/ckan/venv/src/ckan/dev-requirements.txt

# Install ckan extensions
RUN /usr/lib/ckan/venv/bin/pip install -r /requirements.txt

# Extra requirements files for ckan extensions
RUN /usr/lib/ckan/venv/bin/pip install -r /usr/lib/ckan/venv/src/ckanext-dcat/requirements.txt
RUN /usr/lib/ckan/venv/bin/pip install -r /usr/lib/ckan/venv/src/ckanext-spatial/pip-requirements.txt
# RUN /usr/lib/ckan/venv/bin/pip install -r /usr/lib/ckan/venv/src/ckanext-spatial/doc-requirements.txt
RUN /usr/lib/ckan/venv/bin/pip install -r /usr/lib/ckan/venv/src/ckanext-harvest/dev-requirements.txt
RUN /usr/lib/ckan/venv/bin/pip install -r /usr/lib/ckan/venv/src/ckanext-harvest/pip-requirements.txt

# Defra plugin
COPY ./ckanext-defra /usr/lib/ckan/venv/src/ckanext-defra
RUN /usr/lib/ckan/venv/bin/pip install -r /usr/lib/ckan/venv/src/ckanext-defra/dev-requirements.txt

# Need to be root to create the egg file
USER root
RUN /usr/lib/ckan/venv/bin/pip install -e /usr/lib/ckan/venv/src/ckanext-defra/

# Copy init file
COPY ./compose/ckan/ckan-entrypoint.sh /ckan-entrypoint.sh
RUN chmod a+x /ckan-entrypoint.sh


# Initialise the reports
#RUN /usr/lib/ckan/venv/bin/paster --plugin=ckanext-report report initdb -c /etc/ckan/production.ini
#
## Setup tracking cronjob
#RUN /usr/lib/ckan/venv/bin/paster --plugin=ckan tracking update -c /etc/ckan/production.ini && /usr/lib/ckan/venv/bin/paster --plugin=ckan search-index rebuild -r -c /etc/ckan/production.ini"

ENTRYPOINT ["/ckan-entrypoint.sh"]

