---

  
- name: install packages for CKAN
  become: true
  apt:
      pkg: "{{ item }}"
      state: present
      update_cache: true
  with_items:
    - build-essential
    - nginx    
    - libapache2-mod-wsgi
    - libpq5
    - redis-server
    - screen
    - tree
    - vim
    - git-core


- name: Creates deploy directory
  file: path=deploy state=directory

- name: Check if ckan is installed
  command: dpkg-query -W python-ckan_2.8-xenial_amd64
  register: ckan_deb_check
  failed_when: ckan_deb_check.rc > 1
  changed_when: ckan_deb_check.rc == 1

- name: Download ckan.deb
  get_url: 
    url="http://packaging.ckan.org/python-ckan_2.8-xenial_amd64.deb"
    dest="deploy/python-ckan_2.8-xenial_amd64.deb"
  when: ckan_deb_check.rc == 1  

- name: Install ckan.deb
  apt: deb="deploy/python-ckan_2.8-xenial_amd64.deb"
  become: true
  when: ckan_deb_check.rc == 1  

- name: Enable modwsgi 
  become: true 
  command: a2enmod wsgi
  notify: restart apache

- name: Copy the .ini file 
  become: true
  template:
      src: files/production.ini
      dest: /etc/ckan/default/production.ini

- name: Install the ckanext-defra extension 
  become: true
  pip:
    editable: true
    virtualenv: /usr/lib/ckan/default/
    name: file:///vagrant/src/ckanext-defra

- name: symlink ckan schema
  become: true
  file:
    src: "/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml"
    dest: "/etc/solr/conf/schema.xml"
    state: link
    force: yes
  notify: restart solr

- name: Initialise the database
  become: true 
  command: "ckan db init && touch deploy/db_init" 
  args:
    creates: deploy/db_init

- name: restart the things part 1 
  become: true
  service:
    name: apache2
    state: restarted

- name: restart the things part 2
  become: true
  service:
    name: nginx 
    state: restarted

