---


- name: install packages for CKAN
  become: true
  apt:
      pkg: "{{ item }}"
      state: present
      update_cache: true
  with_items:
    - build-essential
    - nginx
    - libapache2-mod-wsgi
    - libpq5
    - redis-server
    - screen
    - tree
    - vim
    - git-core
    - supervisor
    - python-dev
    - libxml2-dev
    - libxslt1-dev
    - libgeos-c1v5


- name: Ensure redis is running
  become: true
  service:
    name: redis-server
    state: restarted

- name: Make sure harvest logging folder exists
  become: true
  file: path=/var/log/ckan/std/ state=directory

- name: Ensure supervisor is running
  become: true
  service:
    name: supervisor
    state: restarted

- name: Creates deploy directory
  file: path=deploy state=directory

- name: Check if ckan is installed
  command: dpkg-query -W python-ckan_2.8-xenial_amd64
  register: ckan_deb_check
  failed_when: ckan_deb_check.rc > 1
  changed_when: ckan_deb_check.rc == 1

- name: Download ckan.deb
  get_url:
    url="http://packaging.ckan.org/python-ckan_2.8-xenial_amd64.deb"
    dest="deploy/python-ckan_2.8-xenial_amd64.deb"
  when: ckan_deb_check.rc == 1

- name: Install ckan.deb
  apt: deb="deploy/python-ckan_2.8-xenial_amd64.deb"
  become: true
  when: ckan_deb_check.rc == 1

- name: Enable modwsgi
  become: true
  command: a2enmod wsgi
  notify: restart apache

- name: Copy the .ini file
  become: true
  template:
      src: files/production.ini
      dest: /etc/ckan/default/production.ini

- name: Install the ckanext-defra extension
  become: true
  pip:
    editable: true
    virtualenv: /usr/lib/ckan/default/
    name: file:///vagrant/src/ckanext-defra

# Harvesting ##########################################################

- name: Install the ckanext-harvesting extension
  become: true
  pip:
    editable: true
    virtualenv: /usr/lib/ckan/default/
    name: file:///vagrant/src/ckanext-harvest

- name: Install the harvesting requirements
  become: true
  command: "/usr/lib/ckan/default/bin/pip install -r /vagrant/src/ckanext-harvest/pip-requirements.txt"
  args:
    creates: deploy/harvest_req_init

- name: Mark deps installed
  become: true
  copy:
    content: ""
    dest: /home/vagrant/deploy/harvest_req_init
    force: no
    group: sys
    owner: root
    mode: 0555

- name: Copy the supervisor config
  become: true
  template:
      src: files/ckan_harvesting.conf
      dest: /etc/supervisor/conf.d/ckan_harvesting.conf

- name: "Start supervisor tasks (1/2)"
  become: true
  command: service supervisor reload
  args:
    warn: no

- name: "Start supervisor tasks (2/2)"
  become: true
  command: supervisorctl restart all

- name: "Setup harvest cronjob"
  cron:
    name: "harvester run"
    minute: "*/10"
    job: "/usr/lib/ckan/default/bin/paster --plugin=ckanext-harvest harvester run --config=/etc/ckan/default/production.ini"

########################################################################
# Spatial  #############################################################

- name: Install the ckanext-spatial extension
  become: true
  pip:
    editable: true
    virtualenv: /usr/lib/ckan/default/
    name: file:///vagrant/src/ckanext-spatial

- name: Install the spatial requirements
  become: true
  command: "/usr/lib/ckan/default/bin/pip install -r /vagrant/src/ckanext-spatial/pip-requirements.txt"
  args:
    creates: deploy/spatial_req_init

- name: Mark deps installed
  become: true
  copy:
    content: ""
    dest: /home/vagrant/deploy/spatial_req_init
    force: no
    group: sys
    owner: root
    mode: 0555

########################################################################
# Database tasks #######################################################

- name: Initialise the database
  become: true
  command: "ckan db init"
  args:
    creates: deploy/db_init

- name: ensure file exists
  become: true
  copy:
    content: ""
    dest: /home/vagrant/deploy/db_init
    force: no
    group: sys
    owner: root
    mode: 0555

- name: Initialise the harvesting database
  become: true
  command: "ckan --plugin=ckanext-harvest harvester initdb -c /etc/ckan/default/production.ini"
  args:
    creates: deploy/harvest_db_init

- name: ensure file exists
  become: true
  copy:
    content: ""
    dest: /home/vagrant/deploy/harvest_db_init
    force: no
    group: sys
    owner: root
    mode: 0555

- name: Change postgis permissions (1/2)
  become: true
  become_user: postgres
  command: "psql -d ckan_default -c 'ALTER VIEW geometry_columns OWNER TO ckan_default;'"
  args:
    creates: deploy/postgis_init

- name: Change postgis permissions (2/2)
  become: true
  become_user: postgres
  command: "psql -d ckan_default -c 'ALTER TABLE spatial_ref_sys OWNER TO ckan_default;'"
  args:
    creates: deploy/postgis_init

- name: ensure file exists
  become: true
  copy:
    content: ""
    dest: /home/vagrant/deploy/postgis_init
    force: no
    group: sys
    owner: root
    mode: 0555

- name: Initialise the spatial database
  become: true
  command: "ckan --plugin=ckanext-spatial spatial initdb 4326 -c /etc/ckan/default/production.ini"
  args:
    creates: deploy/spatial_db_init

- name: ensure file exists
  become: true
  copy:
    content: ""
    dest: /home/vagrant/deploy/spatial_db_init
    force: no
    group: sys
    owner: root
    mode: 0555

########################################################################

- name: restart the things part 1
  become: true
  service:
    name: apache2
    state: restarted

- name: restart the things part 2
  become: true
  service:
    name: nginx
    state: restarted

